import { expect, test } from "@playwright/test";

test("front desk, one recorded spin, checkpoint, collection and portable archive", async ({ page }, testInfo) => {
  await page.goto("/?seed=8");
  await expect(page.getByRole("navigation", { name: "主菜单" })).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath("frontdesk-desktop.png"), fullPage: true });
  await page.getByRole("button", { name: "开始新局" }).click();
  await page.getByRole("dialog", { name: "恢复上次进度" }).getByRole("button", { name: "继续游戏" }).click();
  await page.getByRole("group", { name: "选择服务" }).getByRole("button", { name: /深夜厨房/ }).click();
  await page.getByRole("button", { name: "拉动老虎机", exact: true }).click();
  await page.getByRole("button", { name: "收下这把", exact: true }).click();
  await page.getByRole("button", { name: "直接结算", exact: true }).click();
  await expect(page.getByRole("region", { name: "当前决策" })).toHaveAttribute("data-phase", "READY_TO_SPIN");
  await page.getByRole("button", { name: "完整日志", exact: true }).click();
  await expect(page.getByText("选择服务 · 深夜厨房")).toBeVisible();
  await page.getByRole("button", { name: "核验记录一致性" }).click();
  await expect(page.getByRole("status")).toContainText("核验通过");
  const downloadPromise = page.waitForEvent("download");
  await page.getByRole("button", { name: "导出完整复盘包" }).click();
  const download = await downloadPromise;
  const archivePath = testInfo.outputPath("test-run.json");
  await download.saveAs(archivePath);
  await page.screenshot({ path: testInfo.outputPath("full-log.png"), fullPage: true });
  await page.getByRole("button", { name: "返回", exact: true }).click();
  await page.getByText(/存档与种子/).click();
  await page.getByLabel("备份名称").fill("冒烟测试检查点");
  await page.getByRole("button", { name: "保存手动备份" }).click();
  await expect(page.getByRole("status").filter({ hasText: "备份已保存" })).toBeVisible();
  await page.getByRole("button", { name: "返回前台" }).click();
  await page.getByRole("button", { name: "历史与存档" }).click();
  await expect(page.getByRole("heading", { name: "冒烟测试检查点" })).toBeVisible();
  await page.getByLabel("导入复盘包").setInputFiles(archivePath);
  await expect(page.getByRole("status")).toContainText("已导入为独立档案");
  await expect(page.getByRole("heading", { name: "新夜班 · 8 · 导入" })).toBeVisible();
  await page.getByRole("button", { name: "收藏图鉴", exact: true }).click();
  await page.getByLabel("搜索部件").fill("柠檬感染");
  await page.getByRole("button", { name: "收藏部件" }).click();
  await page.getByLabel("只看收藏的部件").check();
  await expect(page.getByRole("heading", { name: "柠檬感染" })).toBeVisible();
  await page.getByRole("button", { name: "前台", exact: true }).click();
  await page.setViewportSize({ width: 320, height: 740 });
  await page.screenshot({ path: testInfo.outputPath("frontdesk-mobile.png"), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(320);
  await page.reload();
  await expect(page.getByRole("button", { name: "继续游戏", exact: true })).toBeVisible();
});
